apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: crossplane-cluster
  labels:
     service: gke
     creation: crossplane
spec:
  forProvider:
    addonsConfig:
      networkPolicyConfig:
        disabled: false
    networkSelector:
       matchLabels:
           service: vpc 
           creation: crossplane
    subnetworkSelector:
       matchLabels:
           service: subnetwork
           creation: crossplane
    location: us-central1-c #change if required
    ipAllocationPolicy:
      useIpAliases: true
    masterAuth:
      clientCertificateConfig:
        issueClientCertificate: false
    defaultMaxPodsConstraint:
       maxPodsPerNode: 110
    networkPolicy:
      enabled: false
    resourceLabels:
       owner: crossplane
  providerConfigRef:
        name: default-gcp
---
apiVersion: container.gcp.crossplane.io/v1beta1
kind: NodePool
metadata:
  name: crossplane-np
spec:
  forProvider:
    autoscaling:
      autoprovisioned: false
      enabled: false
    clusterSelector:
      matchLabels:
        service: gke
        creation: crossplane
    config:
      machineType: e2-medium #change if required
      diskSizeGb: 100 #change if required
      diskType: pd-standard #change if required
      imageType: COS_CONTAINERD 
      labels:
        owner: crossplane
    initialNodeCount: 2 #change if required
    maxPodsConstraint:
        maxPodsPerNode: 110
    locations:
      - "us-central1-c" #change if required
  providerConfigRef:
         name: default-gcp
